### PR TITLE
Fix article overflow in repostiories in home page  

### LINKED ISSUE #946: Fix overflows in main page
**Is your feature request related to a problem? Please describe.**
image

**Describe the solution you'd like**
No overflows

**Describe alternatives you've considered**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by akshay-ap**
Fixes #946

Changes proposed in this PR:

- Changes in css

### CODE REVIEW

**Comment by akshay-ap** [comment]
image

**Comment by kremalicious** [comment]
the overflow pattern here was intended, think Netflix rows:

Screen Shot 2022-04-12 at 12 12 57

So what is the reason for removing it? Looks like what you want is hiding the scrollbars instead of trying to overwrite the layout altogether. Then look into CSS required to do just that in all modern browser engines.

In any case, lots of weird mobile layout with this PR:

Screen Shot 2022-04-12 at 12 01 40

If the intention is to remove overflow layout all together, then solution is to remove CSS code and create a completely new layout here, not add more CSS to overwrite

**Comment by AnaLoznianu** [comment]
The layout we have now is a bit off. On the left side, we have this large space(you can see in the screenshot) but on the right, we have items that overflow. 

I like the idea of being like the Netflix bar, but we need to somehow adjust the layout to fit better the screen.

Screenshot 2022-04-13 at 10 15 12

**Comment by akshay-ap** [comment]
@AnaLoznianu @kremalicious 
how about this? 
image

Also, the UI now looks consistent across different resolutions on Firefox browser.

**Comment by AnaLoznianu** [comment]
IMHO it looks better this way, but I'll defer this decision to @kremalicious

**Review by AnaLoznianu — APPROVED** [review]

**Comment by kremalicious** [comment]
sorry, but multiple months but I don't see any improvement compared to live. 

This PR makes things worse with that layout, this PR:\
Screen Shot 2022-06-21 at 09 59 28

Live:

Screen Shot 2022-06-21 at 09 59 42

PR also don't remove any overflow as the PR title suggests. So not really sure what the point of all the work going into here is. So closing for now

**Pull request closed without merging**
