### PR TITLE
Remove Ocean Market docs (NOT remaining Predictoor docs)

### PR DESCRIPTION
**Pull request by andreaarmanni**
Updating documentation by removing Ocean Market-related information ~~and predictoor-related information~~.

About market docs:
- Market docs moved to Market Repo via [#2025](https://github.com/oceanprotocol/market/pull/2025)

About Predictoor docs:
- Q: Update Predictoor Docs?
- A: No, they've already been updated
- Details: Most Ocean Predictoor docs have moved to [pdr-docs repo](https://github.com/oceanprotocol/pdr-docs). But people who come to docs.oceanprotocol.com looking for Predictoor docs should be able to readily find them. Therefore we have left a single page for Predictoor docs, that shows the user the location of the Predictoor docs. This should not be deleted or modified further. (See [comment below](https://github.com/oceanprotocol/docs/pull/1435#pullrequestreview-1985914498).)

NOTE: PR to be approved once (a) [#2025](https://github.com/oceanprotocol/market/pull/2025) is closed, and (b) the predictoor changes are reverted in the PR

### CODE REVIEW

**Review by trentmc — CHANGES_REQUESTED** [review]
Predictoor docs updated has been handled already. What's remaining is _supposed_ to be there. Please don't remove it. Therefore @andreaarmanni please update your PR, such that the remaining Predictoor stuff _isn't_ deleted.

 Details:
- Issue [#1426](https://github.com/oceanprotocol/docs/issues/1426) "[Pdr] Reconcile pdr-related docs with docs.predictoor.ai"
- PR https://github.com/oceanprotocol/docs/pull/1428
- Commit https://github.com/oceanprotocol/docs/commit/eb9f50109a06168dc17737bb941d0bb1b0662f9c

**Comment by mihaisc** [comment]
Trent is correct, my bad

**Comment by mihaisc** [comment]
you also need to update summary.md

**Comment by andreaarmanni** [comment]
> you also need to update summary.md

Yep, found also another couple links. It should be all good now. 

Sorry - never worked on the docs so still getting familiar with this. Thanks

**Review by andreaarmanni — COMMENTED** [review]
Updated PR with requested changes

**Review by trentmc — APPROVED** [review]
I will focus on the Predictoor side. This PR no longer has the PR changes. Great! That's how it should be.

I marked "approve" as in "approved wrt Predictoor". But not wrt market-related part.  For that, I defer to @mihaisc or others more deeply involved.

**Pull request merged**
