### PR TITLE
Revise & add docs now that we support three storage options

### PR DESCRIPTION
**Pull request by ttmc**
This is one in a set of several pull requests to clarify how to use all the different Brizo storage options.

- Updated some text which said (or implied) we only support Azure storage.
- In the Marketplace setup page, made it clear that three storage providers are supported.
- Added two new tutorial pages, one for Amazon S3 storage setup and one for on-premise storage setup.
- Updated the git submodules because I recently updated the tutorial page about how to set up Azure storage (in the dev-ocean repo): oceanprotocol/dev-ocean#125
- **npm run format** also did some minor edits.

### CODE REVIEW

**Comment by ttmc** [comment]
@Pedro-vk or @kremalicious the docs build is failing when it tries to build the squid-js docs. I guess it's because I updated the squid-js git submodule (external repository commit hash) as part of this pull request. I guess you would know how to fix the problem that arose:

```bash
- Generating TypeDoc json...
Error: The tsconfig file  does not exist.
fs.js:119
    throw err;
    ^
Error: ENOENT: no such file or directory, stat '/home/travis/build/oceanprotocol/docs/external/squid-js/src/squid.ts'
    at Object.statSync (fs.js:871:3)
    at inputFiles.forEach (/home/travis/build/oceanprotocol/docs/node_modules/typedoc/dist/lib/application.js:127:20)
    at Array.forEach (<anonymous>)
    at Application.expandInputFiles (/home/travis/build/oceanprotocol/docs/node_modules/typedoc/dist/lib/application.js:125:20)
    at generateJson (/home/travis/build/oceanprotocol/docs/scripts/typedoc.js:43:21)
    at ChildProcess.install.on (/home/travis/build/oceanprotocol/docs/scripts/typedoc.js:32:5)
    at ChildProcess.emit (events.js:197:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @oceanprotocol/docs@0.0.1 typedoc: `node ./scripts/typedoc.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @oceanprotocol/docs@0.0.1 typedoc script.
```

**Comment by kremalicious** [comment]
not sure what happened with the submodule, I just updated it to latest hash in `release` branch and now this PR shows no differences in squid-js compared to `master` and build works again 🤷‍♂️

**Comment by ttmc** [comment]
A note for the reviewers: In the future, I intend to make the tutorials for setting up Amazon S3 storage and on-premise storage more detailed (with a long example). I want to get this update published soon because saying _something_ about the S3 and on-premise storage options is better than nothing.

**Comment by ttmc** [comment]
@MarcusJones I revised the definition of "Asset or Data Asset" on the Terminology page to something that's more general and hopefully better. I also linked to that definition from many more occurrences of "asset" or "assets" in the docs.

**Pull request merged**
