### PR TITLE
Trigger rebuild to deploy ocean.py v0.7.0 docs

### PR DESCRIPTION
**Pull request by DMats**
Towards https://github.com/oceanprotocol/ocean.py/issues/497

### CODE REVIEW

**Comment by DMats** [comment]
@akshay-ap While reviewing the [preview](https://deploy-preview-775--docs-oceanprotocol.netlify.app/?utm_source=github&utm_campaign=bot_dp), I noticed that the main docs page still shows the old ocean.py version v0.6.0
Screenshot from 2021-09-24 10-01-00

Similarly the API Reference Overview page shows the old version as well:
Screenshot from 2021-09-24 10-03-57

Happily, the detailed API reference for ocean.py has been updated to the new v0.7.0. 
Screenshot from 2021-09-24 10-00-32

I'm wondering, is there a way to make sure the main docs page and API Reference Overview pages get updated?

**Comment by trentmc** [comment]
It's step 0 in release process documentation
https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/release-process.md

**Comment by DMats** [comment]
@trentmc Thanks for taking a look!  
I completed step 0 of the ocean.py/release-process.md in https://github.com/oceanprotocol/readthedocs/pull/29.  And when I grep through the `readthedocs` repo, main branch, I can't find any instances of the string `v0.6.0`

**Comment by trentmc** [comment]
> EDIT: So my theory is that set 6 of https://github.com/oceanprotocol/readthedocs#readme might be missing a step somewhere.

Ideas? Solve it if you can.

Maybe @akshay-ap can help?

**Comment by akshay-ap** [comment]
@trentmc @DMats , I have fixed the issue. We recently provided a fix for failing builds due to draft releases. The `splice` function took second entry from the array of releases. Ideally 1st entry should have been picked using `splice`. Should be fine now.

**Comment by DMats** [comment]
Thanks, @akshay-ap!  I just checked the preview and can attest that the version numbers on the main docs page and the API Reference Overview page are now correct.

**Review by akshay-ap — APPROVED** [review]

**Pull request merged**
