### PR TITLE
Feature/read the docs

### LINKED ISSUE #527: ocean.js API docs are not rendered
Ocean.js API docs page is rendered blank: https://docs.oceanprotocol.com/references/ocean.js

### PR DESCRIPTION
**Pull request by akshay-ap**
Fixes #527, #646

Changes proposed in this PR:

- Render Ocean.js docs
- Add ocean-subgraph readmes
- Add version in footer

### CODE REVIEW

**Comment by akshay-ap** [comment]
image

**Comment by akshay-ap** [comment]
image

**Comment by trentmc** [comment]
ocean.js looks great.

And it's nice to see progress on Ocean subgraph documentation.

An error to fix: in the Ocean subgraph README, clicking these links does nothing:

- 🧶 Example Queries
- 🦑 Development
- 🦑 Development on barge
- 🧪 Testing
- 🛳 Releases

**Review by trentmc — DISMISSED** [review]
Changes requested - see my previous comment

**Comment by akshay-ap** [comment]
hi @trentmc ,

I checked and found that few emojis in Markdown headers are not removed by the gatsby plugin: `gatsby-remark-autolink-headers`.

Gatsby is not removing 🧶 and other emojis during build. 
e.g.

Actual:
https://deploy-preview-656--docs-oceanprotocol.netlify.app/read-the-docs/ocean-subgraph/#🧶-example-queries

Expected:
https://deploy-preview-656--docs-oceanprotocol.netlify.app/read-the-docs/ocean-subgraph/#-get-started

I think this is a bug in the plugin.
Immediate fix would be to remove the emojis from the markdown headers.

**Comment by akshay-ap** [comment]
I think this is due to bug in `gatsby-remark-autolink-headers` plugin. Certain emojis (e.g. 🏄) are omitted from urls and we don't have any issue. But, some are not (e.g. 🧶, 🦑, 🧪, 🛳) and causing the issue. I will confirm whether this is really a bug.

**Comment by trentmc** [comment]
This is great news: simply choose a set of ocean-themed emojis that don't cause issues. Problem solved:)

**Review by alexcos20 — APPROVED** [review]

**Pull request merged**
