### PR TITLE
Feature: Render example JSON response

### LINKED ISSUE #695: Adapt docs to render sample api responses of Aquarius
**Is your feature request related to a problem? Please describe.**
1. The docs here do not render sample api responses of Aquarius: https://docs.oceanprotocol.com/references/aquarius/ and thus making it unclear what api exactly returns.

2. There are no docstrings for example in Aquarius source code that can be rendered.
3. 
- We are using `swagger` spec to render [rest api docs](https://docs.oceanprotocol.com/references/aquarius/) which uses `yml` style in docstrings.
- We use `pydoc-markdown` to generate [Aquarius Py Modules](https://docs.oceanprotocol.com/references/read-the-docs/aquarius/) which uses Sphinx Style to generate markdowns. 

Above formats are not compatible and causes issue in rendering docs.

e.g. In Aquarius py modules,
image

**Describe the solution you'd like**
- [ ] Add docstrings in for sample responses in Aquarius source code
- [ ] Adapt doc repository to render the responses.
- [ ] Remove `Aquarius Py Module docs` https://docs.oceanprotocol.com/references/read-the-docs/aquarius/ 

e.g after adding content and adapting docs:

image

**Describe alternatives you've considered**

**Additional context**

Related to Aquarius issue: https://github.com/oceanprotocol/aquarius/issues/538

### PR DESCRIPTION
**Pull request by akshay-ap**
Fixes #695 

Changes proposed in this PR:

- Adapt docs repository to render examples from swagger spec

### CODE REVIEW

**Comment by kremalicious** [comment]
I do not see any changes on the deploy preview

- https://deploy-preview-696--docs-oceanprotocol.netlify.app/references/aquarius is exactly same as
- https://docs.oceanprotocol.com/references/aquarius/

**Comment by akshay-ap** [comment]
@kremalicious, we have the `Aquarius` doc string improvements released under `3.0.2` version. But, current version of `Aquarius` is 2.2.12 in mainnet. After mainnet is updated, swagger spec will have sample api responses.

**Comment by kremalicious** [comment]
`aquarius.mainnet.oceanprotocol.com` will never be updated, see the [multi network blog post](https://blog.oceanprotocol.com/ocean-makes-multinetwork-even-simpler-c3ec6c0cbd50) under _Migration to Multi-Network Aquarius_

This means we have to also switch to `aquarius.oceanprotocol.com` here in the docs

**Comment by akshay-ap** [comment]
We have an issue here for changing swagger url: https://github.com/oceanprotocol/docs/issues/716

**Comment by akshay-ap** [comment]
@alexcos20 To close this PR following url should have Aquarius 3.0.1: https://aquarius.oceanprotocol.com/
Can we upgrade to Aquarius 3.0.1?

**Comment by trentmc** [comment]
This is pending Aquarius 3.0.1.

Once that's ready, we can un-convert from a draft, and request review.

**Comment by akshay-ap** [comment]
Snippet of feature:
image

**Comment by trentmc** [comment]
> This is pending Aquarius 3.0.1.

This is now ready. 

Therefore we can approve the PR.

**Review by trentmc — APPROVED** [review]

**Pull request merged**
