### PR TITLE
projects page

### PR DESCRIPTION
**Pull request by kremalicious**
Fixes https://github.com/oceanprotocol/multi-repo-issue/issues/60

Also adds a pr-commit hook which will run `npm run format` before every Git commit, which should prevent simple formatting and syntax errors

### CODE REVIEW

**Comment by trentmc** [comment]
> Fixes oceanprotocol/multi-repo-issue#60

We are currently in disagreement on this. See that issue's comments section. This PR should not be merged until we are in sync.

**Comment by trentmc** [comment]
Here's my proposal to move this issue forward:

* Start with this PR
* Tweak this PR, such that at the top of the page, there's steps of how to contribute. Something like:

"If you'd like to add to this list, please submit a pull request (PR) to [this file in GitHub](https://github.com/oceanprotocol/docs/tree/main/content/concepts/projects-using-ocean.md). PR instructions are in [this repo's README](https://github.com/oceanprotocol/docs)".

**Comment by trentmc** [comment]
> there's steps of how to contribute ..

I had a look. I realize now that there's already a link on the bottom "Edit this page on github". So no more needed.

I'm satisfied with this now.

**Review by trentmc — APPROVED** [review]

**Comment by kremalicious** [comment]
well, can't hurt, just added a note, check out the shiny new Vercel preview links https://docs-git-feature-projects.oceanprotocol.vercel.app/concepts/projects-using-ocean/

**Comment by trentmc** [comment]
> well, can't hurt, just added a note

Oh cool :) :)

**Comment by trentmc** [comment]
I realized that I may have prematurely closed this:

The only way I can find the page is if I know the exact url.

That is, there doesn't seem to be a link from the menu bar on the left. (Or at least I can't find it.)

Is it there, or did I miss it?

**Review by trentmc — APPROVED** [review]

**Comment by trentmc** [comment]
Looks good! Would you like to merge the PR / delete branch / close the issue?

**Pull request merged**
